apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
data:
  POSTGRES_HOST: "cafanwii-postgres-sosotech.io"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "sonarqube"
  POSTGRES_USER: "cafanwiiuser"