apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarqube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarqube
  template:
    metadata:
      labels:
        app: sonarqube
    spec:
      containers:
      - name: sonarqube
        image: sonarqube:latest
        ports:
        - containerPort: 9000
        env:
        - name: SONARQUBE_JDBC_URL
          value: jdbc:postgresql://cafanwii-postgres-sosotech.io/sonarqube:5432/sonar 
          # "jdbc:postgresql://cafanwii-postgres-sosotech.io/sonarqube?socketTimeout=1500" 
        - name: SONARQUBE_JDBC_USERNAME
          value: cafanwiiuser
        - name: SONARQUBE_JDBC_PASSWORD
          value: Depay20$
  #       volumeMounts:
  #       - name: sonarqube-data
  #         mountPath: /opt/sonarqube/data
  # volumes:
  # - name: sonarqube-data
  #   persistentVolumeClaim:
  #     claimName: sonarqube-pv-claim
