apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarqube-postgresql-pv
spec:
  capacity:
    storage: 8Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: hostpath
  hostPath:
    path: "/cafanwii/postgresql-data"
