version: '3.8'
services:

  keycloak:
    image: quay.io/keycloak/keycloak:25.0.0
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      PROXY_ADDRESS_FORWARDING: "true"
    ports:
      - "8080:8080"
      - "8443:8443"
    volumes:
      - "./tls.key:/etc/x509/https/tls.key"
      - "./tls.crt:/etc/x509/https/tls.crt"
      - "./keycloak-latest-db:/opt/jboss/keycloak/standalone/data"
